### ISSUE TITLE
Ready up is off center

### ISSUE THREAD

**Issue by jas1992fasolastudent** [Hypnootize/m0rehud#13]
as shown in picture below

![image](https://user-images.githubusercontent.com/107649152/174156238-8404fc94-d651-43ab-8c85-753eacd7a6e7.png)

**Comment by Hypnootize** [comment]
You took the screenshot during a 5v6 so that's why you measurement looks off, if you focus on the gap between the red and blue players it looks to be pretty centered. That said I don't really change anything related to that, the game does that by itself and since the tournament panel is set to cover the entire screen it will center it based on that, which mean it should be perfectly cenetered as shows here:
![test](https://user-images.githubusercontent.com/19785551/174353738-244125da-0a6f-4c05-b2d3-5cfcf842aa16.png)

**Comment by jas1992fasolastudent** [comment]
yes i meant the check image, thanks for the answer

**Comment by Hypnootize** [comment]
Yeah the white rectangle threw me off at first and I ended up overcomplicating the matter quite a bit, lol sorry. It should be fixed now, thanks!
