### ISSUE TITLE
tf_use_match_hud is not showing health

### ISSUE THREAD

**Issue by billw1** [Hypnootize/m0rehud#15]
I even tried adding the customization ([MatchStatus] HealthBar Static (DefaultON)). It still just shows team colours behind the class icons regardless of health.

**Comment by Hypnootize** [comment]
Apparently this was caused by the health bar being too wide, ["healthbar"](https://github.com/Hypnootize/m0rehud/blob/master/resource/ui/hudmatchstatus.res#L239) was "wide" "99999" (most likely a misstype on my part) which made it invisible for certain resolutions, editing it to "9999" seems to fix the problem.
