### ISSUE TITLE
Loading Screen Background not working

### ISSUE THREAD

**Issue by DeathLMAO** [Hypnootize/m0rehud#44]
While attempting to create a custom loading screen, it does not seem to function as intended, I get the purple missing texture error that seems to attempt to load something. I have it in the correct file location using the VTF format and with the included loading_bg.VMT, I've tried removing the included loading_bg.VMT, I've tried different images to be saved as the VTF. Had the settings as the guide shows. But still missing texture. Please let me know if I am missing a step that might have been omitted on accident on the guide or maybe the file size limit?

**Comment by Hypnootize** [comment]
I've just tried and it seems to be working fine for me, however, I have seen this happen before and it was caused by VTF Edit Reloaded using the wrong version, try to re-import the image and in the import settings, under the advanced tab, select the 7.0 version then save as `.vtf` and move it `m0rehud\Materials\VGUI\Replay\Thumbnails\Menu` just like you did before.

![VTF Options](https://github.com/Hypnootize/m0rehud/assets/19785551/9aca2e02-d93c-45c1-9c1f-92544ff86f9e)

Also the `.vmt` is needed and it's what the game looks for, so even if the `.vtf` now works but the `.vmt` is missing it will still display the missing textures, make sure to add that back in case you still have it removed!

**Comment by DeathLMAO** [comment]
Changing to to version 7.0 did make it work. Thank you! Maybe add this mention to the wiki since VTF Edit Reloaded defaults to 7.5. But again thank you for the quick response!

**Comment by Hypnootize** [comment]
I'm glad it worked! It's now specified in the wiki as well.
