### ISSUE TITLE
unable to change ypos of "AmmoInReserve" in hudammoweapons_base.res

### ISSUE THREAD

**Issue by r3dnasa** [Hypnootize/m0rehud#50]
not sure why but no matter what value i set the ypos of "AmmoInReserve" the ammo stays in place despite every other element being able to be moved

![20240307044530_1](https://github.com/Hypnootize/m0rehud/assets/82971054/9328c829-7ce2-42df-9ec9-5eb8f2c1a5ed)
![image](https://github.com/Hypnootize/m0rehud/assets/82971054/361f43ef-c987-4f3a-b292-f48bea8f5b8a)

![20240307044647_1](https://github.com/Hypnootize/m0rehud/assets/82971054/46ccb5f1-ebcd-464e-acd6-3420ab5bee53)
![image](https://github.com/Hypnootize/m0rehud/assets/82971054/c664eb75-7d68-4f4d-b376-544f5f6b4918)

**Comment by Hypnootize** [comment]
It's caused by the customization file overriding `hudammoweapons_base.res` mostly because with the smaller font the reserve ammo was a bit off. 

You can edit the ypos from `Resource/UI/Customizations/Ammo/HudAmmoWeapons_Font_Small.res` or you could even delete the ypos inside it so you can then edit it from `hudammoweapons_base.res` directly, up to you.

**Comment by r3dnasa** [comment]
Ohh okay, thank you
