### ISSUE TITLE
Revert Tools Bar Changes

### ISSUE THREAD

**Issue by blakeplusplus** [Hypnootize/m0rehud#51]
You have rolled "Fix Invisible Players", "Reload Sound", and "Reload HUD" into one button. Please revert this change by putting "Reload HUD" and "Reload Sound" into one button and "Fix Invisible Players" as another.

Reasoning: For competitive players, if I have a HUD or sound glitch, I simply want to fix that glitch during a match and do nothing else. However, since all fixes are rolled into one, this forces me to also stop the demo I'm recording and start recording a new one, even though this isn't needed. This makes finding demos later on for submission for anticheat more difficult, as well as making it harder to find clips for fragmovies and such after the fact.

**Comment by Hypnootize** [comment]
I agree and I'll revert that, didn't put too much thought when I did that and then I ended up mostly forgetting about it.

On another note, is the "Fix Invisible Players" even needed? I don't really play the game too much anymore while recording demos so I'm not sure if the invisible players bug while recording demos is still a reocurring bug or it got better since then, but I feel like pretty much no one uses that button regardless as there are probably better ways of fixing it depending on how you have your demo recording setup.

**Comment by Hypnootize** [comment]
The button is now set to only reload sound and HUD, I'll see if the invisible players fix is worth bringing back as a separate button in the future

**Comment by blakeplusplus** [comment]
> On another note, is the "Fix Invisible Players" even needed?

A million times yes. The bug still happens quite often. If there are alternative ways to fix it, let me know, but AFAIK doing the command that the Fix Invisible Players button does is the only way to fix it. And it's super convenient. So please add it back or make it a HUD option for competitive players 🙏

**Comment by Hypnootize** [comment]
It think it can be better, like right now it always record a `fix` demo so if run more than once it will overlap the older one making users lose the older demo, that can be easily fixed by using `ds_record` instead I think but I'm not sure if it conflicts with p-rec for anyone that still uses it, that why I originally didn't go for it.
I'll investigate a bit and re-add the button soon.
