### ISSUE TITLE
Strange issue with outline for Crosshairs

### ISSUE THREAD

**Issue by colepaws** [Hypnootize/m0rehud#54]
This has actually been an issue for quite a while and I was hoping it'd get fixed, but it hasn't. In older m0rehud versions I could manually offset the outline and make it match up, but things have changed so much I'm not able to do that anymore. On size 12, the outline cuts off on the right side, and on larger sizes it doesn't fill the outline all the way.
![tf_win64_4BscmnOYc8](https://github.com/Hypnootize/m0rehud/assets/118927649/6a840097-08a2-4f7d-ac70-a7f03d37ea3f)
![tf_win64_VbElZO9iGT](https://github.com/Hypnootize/m0rehud/assets/118927649/6ac31493-182c-44b9-9b54-9a53db388fbe)

**Comment by Hypnootize** [comment]
What did you used to do in order to manually offset the outline? as far as I know you have no control over it as it is drawn automatically by the game with no option to resize and move it.
If you meant to manually adjust size, positioning and all that it's still possible even tho it's a little different. You can do it from `Resource/UI/Customizations/Crosshair/Crosshair_Base.res` just make sure to run `m0_crosshair_reset` in console first as any option previously enabled in the customizations screen will override your manual editing in the file.
Personally when something like this happens with outlines I usually bump the size up or down by one and kinda hope it works as you don't really have much control over it.
